// swift-tools-version: 5.9
// Generated by @kompan-design/token-build. Do not edit.
import PackageDescription

let package = Package(
    name: "KompanTokens",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "KompanTokens", targets: ["KompanTokens"]),
    ],
    targets: [
        .target(name: "KompanTokens", path: "Sources/KompanTokens"),
    ]
)
